name: external-postgres-metrics-emitter
instance_groups:
- azs: [z1]
  instances: 1
  jobs:
  - name: bpm
    release: bpm
  - name: external-postgres-metrics-emitter
    release: external-postgres-metrics-emitter
    properties:
      loggregator:
        tls:
          key: ((loggregator_tls_agent.private_key))
          cert: ((loggregator_tls_agent.certificate))
          ca_cert: ((loggregator_tls_agent.ca))
      database:
        host: ((database.host))
        port: ((database.port))
        username: ((database.username))
        password: ((database.password))
  - name: loggregator_agent
    release: loggregator-agent
    consumes:
      doppler:
        from: doppler
        deployment: ((cf_deployment_name))
    properties:
      grpc_port: 3459
      disable_udp: true
      loggregator:
        tls:
          ca_cert: "((loggregator_tls_agent.ca))"
          agent:
            cert: "((loggregator_tls_agent.certificate))"
            key: "((loggregator_tls_agent.private_key))"
      metrics:
        ca_cert: "((loggregator_agent_metrics_tls.ca))"
        cert: "((loggregator_agent_metrics_tls.certificate))"
        key: "((loggregator_agent_metrics_tls.private_key))"
        server_name: loggregator_agent_metrics
  name: external-postgres-metrics-emitter
  networks:
  - name: default
  stemcell: default
  vm_type: default

releases:
- name: external-postgres-metrics-emitter
  sha1: 2bb150154a2a6207f745c2873c6c1efefb591666
  stemcell:
    os: ubuntu-xenial
    version: "621.92"
  url: https://s3.amazonaws.com/external-postgres-metrics-emitter-release/compiled-releases/external-postgres-metrics-emitter/external-postgres-metrics-emitter-0.0.1-ubuntu-xenial-621.92-20201126-145556-622709339-20201126145558.tgz
  version: 0.0.1
- name: loggregator-agent
  version: latest
- name: bpm
  version: latest
