meta:
  name: external-postgres-metrics-emitter
  target: pipes@main
  url:     https://pipes.starkandwayne.com

  bosh:
    stemcell:
      major: 621
      cpi: warden-boshlite
    target: ((thunder-dome.url))
    username: ((thunder-dome.username))
    password: ((thunder-dome.password))
    cacert: ((thunder-dome.ca-certificate))

  manifest:
    path: ci/testflight.yml

  github:
    owner: starkandwayne
    repo:  external-postgres-metrics-emitter-release
    private_key: ((github.private-key))
    access_token: ((github.access-token))
    webhook_token: ((webhook.token))

  git: 
    email: ci@starkandwayne.com
    name: CI Bot

  aws:
    access_key: "\"((aws.access))\""
    secret_key: "\"((aws.secret))\""

  slack:
    webhook: ((slack.webhook))
    channel: "#botspam"

  go:
    version: 1.15
    
