name: external-postgres-metrics-emitter
instance_groups:
- azs: [z1]
  instances: 1
  jobs:
  - name: postgres
    release: postgres
    properties:
      databases:
        collect_statement_statistics: true
        databases: []
        db_scheme: postgres
        port: 5524
        roles:
        - name: superuser
          password: ((superuser_password))
          permissions:
          - "SUPERUSER"
  - name: bpm
    release: bpm
  - name: external-postgres-metrics-emitter
    release: external-postgres-metrics-emitter
    properties:
      loggregator:
        tls:
          key: ((loggregator_tls_agent.private_key))
          cert: ((loggregator_tls_agent.certificate))
          ca_cert: ((loggregator_tls_agent.ca))
      databases:
      - host: 127.0.0.1
        port: 5524
        username: superuser
        password: ((superuser_password))
  - name: loggregator_agent
    release: loggregator-agent
    consumes:
      doppler:
        from: doppler
    properties:
      grpc_port: 3459
      disable_udp: true
      loggregator:
        tls:
          ca_cert: "((loggregator_tls_agent.ca))"
          agent:
            cert: "((loggregator_tls_agent.certificate))"
            key: "((loggregator_tls_agent.private_key))"
      metrics:
        ca_cert: "((loggregator_agent_metrics_tls.ca))"
        cert: "((loggregator_agent_metrics_tls.certificate))"
        key: "((loggregator_agent_metrics_tls.private_key))"
        server_name: loggregator_agent_metrics
  - name: doppler
    release: loggregator
    provides:
      doppler: {as: doppler, shared: true}
    properties:
      loggregator:
        tls:
          ca_cert: "((loggregator_tls_doppler.ca))"
          doppler:
            cert: "((loggregator_tls_doppler.certificate))"
            key: "((loggregator_tls_doppler.private_key))"
  name: external-postgres-metrics-emitter
  networks:
  - name: default
  stemcell: default
  vm_type: default
releases:
- name: external-postgres-metrics-emitter
  version: latest
- name: loggregator-agent
  url: https://bosh.io/d/github.com/cloudfoundry/loggregator-agent-release?v=6.1.3
  version: 6.1.3
  sha1: df5097de1797ef6e6816823625096a7751e031a1
- name: bpm
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.9
  version: 1.1.9
  sha1: dcf0582d838a73de29da273552ae79ac3098ee8b
- name: loggregator
  url: https://bosh.io/d/github.com/cloudfoundry/loggregator-release?v=106.3.11
  version: 106.3.11
  sha1: c74c945f313a953664f299af63403aae48bd2051
- name: postgres
  sha1: 0a9e4ad424f2ad9611dd1d3f387cc12ed7b71ee4
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=42
  version: "42"
stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest
update:
  canaries: 2
  canary_watch_time: 5000-60000
  max_in_flight: 1
  update_watch_time: 5000-60000
variables:
- name: loggregator_ca
  type: certificate
  options:
    common_name: loggregatorCA
    is_ca: true
- name: loggregator_tls_agent
  type: certificate
  update_mode: converge
  options:
    ca: loggregator_ca
    common_name: metron
    alternative_names:
    - metron
    extended_key_usage:
    - client_auth
    - server_auth
- name: loggregator_tls_doppler
  type: certificate
  update_mode: converge
  options:
    ca: loggregator_ca
    common_name: doppler
    alternative_names:
    - doppler
    extended_key_usage:
    - client_auth
    - server_auth
- name: metric_scraper_ca
  type: certificate
  options:
    common_name: metricScraperCA
    is_ca: true
- name: loggregator_agent_metrics_tls
  type: certificate
  update_mode: converge
  options:
    ca: metric_scraper_ca
    common_name: loggregator_agent_metrics
    alternative_names:
    - loggregator_agent_metrics
    extended_key_usage:
    - server_auth
- name: superuser_password
  type: password
