loggregator:
  metron_address: 127.0.0.1:3459
  tls:
    key_file: "./loggregator_agent.key"
    cert_file: "./loggregator_agent.crt"
    ca_file: "./loggregator_ca.crt"
database:
  host: 127.0.0.1
  port: 5432
  name: postgres
  username: postgres
  password: postgres
