version: "2"
services:
  postgres:
    image: test-postgres
    build: images/postgres
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USERNAME=postgres"
      - "POSTGRES_DATABASE=postgres"
      - "ALLOW_EMPTY_PASSWORD=yes"

  loggregator:
    image: dummymetron
    build: images/dummymetron
    ports:
      - "3459:3459"
    command:
    - "--grpc-port=3459"
volumes:
  postgresql_data:
    driver: local
